React tutorial
MarcoDiaz2000/react-tutorial pull request #1
Opened 2023-06-05 17:10 UTC by MarcoDiaz2000

In this exercise, I consolidated my knowledge about React, components, props, state, and hooks, by following a tutorial.

2023-06-06 17:17 UTC, unorjikingsley commented on src/components/Header.jsx
> +      {props.children}
- [ ] You did a good job working on your Header.jsx 💯 However, please make sure that the {props.children} has the prop validation  kindly use the code below to fix it. 🤓 🔧 

Header.propTypes = {
  children: PropTypes.node.isRequired,
};

2023-06-06 17:17 UTC, unorjikingsley commented on src/components/Header.jsx
> +      {props.children}
- [ ] You did a good job working on your Header.jsx 💯 However, please make sure that the {props.children} has the prop validation  kindly use the code below to fix it. 🤓 🔧 

Header.propTypes = {
  children: PropTypes.node.isRequired,
};

2023-06-06 17:19 UTC, unorjikingsley commented on src/components/InputTodo.jsx
> +const InputTodo = ({ addTodoItem }) => {
- [ ] You did a good job working on your InputTodo.jsx 💯 However, please make sure that the {addTodoItem} has the prop validation  kindly fix it. 🤓 🔧

2023-06-06 17:21 UTC, unorjikingsley commented on src/components/NavbarFirst.jsx
> +      </ul>
- [ ] Please don't forget to remove old pieces of commented code, they make your code base look ugly and make it less readable.  🤓 🔧

2023-06-06 17:24 UTC, unorjikingsley commented on src/components/ProtectedRoute.jsx
> +const ProtectedRoute = ({ children }) => {
- [ ] You did a good job working on your ProtectedRoute.jsx 💯 However, please make sure that the {addTodoItem} has the prop validation  kindly fix it. 🤓 🔧

2023-06-06 17:26 UTC, unorjikingsley commented on src/components/TodoApp.jsx
> +};
- [ ] Great Job. Always remember to remove old pieces of code for readability. 🤓

2023-06-06 17:30 UTC, unorjikingsley commented on src/components/TodoItem.jsx
> +  const handleUpdatedDone = (event) => {
- [ ] You did a good job working on your TodoItem.jsx 💯 However, there are lots of place that needs the prop validation
- [ ] In line 10, you declared `UpdateInput`  but never used it. kindly fix that also. 🤓 🔧

2023-06-06 17:32 UTC, unorjikingsley commented on src/context/AuthContext.jsx
> +  function getUsername() {
- [ ] You did a good job working on your AuthContect.jsx. 💯 However, you declared a getUsername function that was never used. 🤓

2023-06-06 17:45 UTC, unorjikingsley requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @MarcoDiaz2000 , 


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻  

## Required Changes ♻️
_Check the comments under the review._
 - [ ] Please pay attention to props validation, remove commented lines of code and also remove functions that is not in use so that your code is more clean and readable to all.

You can also consider:
- [ ]  Next time, and for future commits, I kindly suggest that you please make your PR more descriptive. Focus on listing the feature in that PR to enable other programmers to understand the journey of building the app.
:x: Bad Commit Messages :x:


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 17:45 UTC, unorjikingsley commented on src/index.css
> +  -webkit-text-size-adjust: 100%;
- [ ] Beware of using code that is not supported in all browser. This is important for users so they dont have bad experience or different experience from others using the app.

2023-06-07 00:36 UTC, MarcoDiaz2000 commented
Hi, @unorjikingsley 
Ok, I will make the requested changes

Thank you

> # STATUS: CHANGES REQUIRED ♻️ 🚧
> Hi @MarcoDiaz2000 ,
> 
> While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️
> 
> You are almost there, keep up the good work! 🚀
> 
> ![](https://camo.githubusercontent.com/1ffb80c92a4b41eda3c73a360964b1cb423c621dedcf0c344ce0f24f8092e3a8/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f68687769323549535843375a34744d732f67697068792d646f776e73697a65642d6d656469756d2e676966) [ ![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f68687769323549535843375a34744d732f67697068792d646f776e73697a65642d6d656469756d2e676966](https://camo.githubusercontent.com/1ffb80c92a4b41eda3c73a360964b1cb423c621dedcf0c344ce0f24f8092e3a8/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f68687769323549535843375a34744d732f67697068792d646f776e73697a65642d6d656469756d2e676966) ](https://camo.githubusercontent.com/1ffb80c92a4b41eda3c73a360964b1cb423c621dedcf0c344ce0f24f8092e3a8/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f68687769323549535843375a34744d732f67697068792d646f776e73697a65642d6d656469756d2e676966) [ ](https://camo.githubusercontent.com/1ffb80c92a4b41eda3c73a360964b1cb423c621dedcf0c344ce0f24f8092e3a8/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f68687769323549535843375a34744d732f67697068792d646f776e73697a65642d6d656469756d2e676966)
> 
> ## Highlights
> ✅ Great use of Git flow. 💯 ✅ Your project is documented professionally. 📜 ✅ Great UI design. 💻
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [ ]  Please pay attention to props validation, remove commented lines of code and also remove functions that is not in use so that your code is more clean and readable to all.
> 
> You can also consider:
> 
> * [ ]   Next time, and for future commits, I kindly suggest that you please make your PR more descriptive. Focus on listing the feature in that PR to enable other programmers to understand the journey of building the app.
>   ❌ Bad Commit Messages ❌
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 13:26 UTC, merged